[build-system]
requires = [
  "setuptools>=80",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["resignation"]

[project]
name = "resignation"
requires-python = ">= 3.12"
description = "re[sign]ation: A script to create digital signatures"
authors = [
  {name = "Max Kurze", email = "Max.Kurze@barkhauseninstitut.org"},
]
maintainers = [
  {name = "Max Kurze", email = "Max.Kurze@barkhauseninstitut.org"}
]
license = { text = "GPLv3" }
dependencies = [
  "pyhanko>=0.25.3",
  "pymupdf>=1.25.2",
  "pillow>=11.2.1",
  "inquirerpy>=0.3.4",
  "pyqt6>=6.9.0",
  "keyring>=25.6.0"
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/maxkurze1/resignation"

[project.scripts]
resignation = "resignation.resignation:main"
